### ISSUE TITLE
Failed to create CSV file with 20000 rows

### ISSUE THREAD

**Issue by zubairov** [elasticio/csv-component#47]
I've build a simple integration flow:

![image](https://user-images.githubusercontent.com/56208/69967959-bd267000-1519-11ea-81d4-9ddbdd6800da.png)

then using simple `load-test` tool loaded 2000 request to it:

```bash
#!/bin/bash
loadtest -c 5 -n 20000 "https://in.elastic.io/hook/5de5199b20ea507fdaf1a542?message=Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum"
```

It run all well:

```
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO Max requests:        20000
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO Concurrency level:   5
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO Agent:               none
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO Completed requests:  20000
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO Total errors:        0
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO Total time:          837.860013091 s
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO Requests per second: 24
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO Mean latency:        209.4 ms
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO Percentage of the requests served within a certain time
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO   50%      201 ms
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO   90%      213 ms
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO   95%      235 ms
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO   99%      400 ms
[Mon Dec 02 2019 15:34:23 GMT+0100 (Central European Standard Time)] INFO  100%      723 ms (longest request)
```

at the end I expected a file to be uploaded to SFTP to have 20.000 rows in it:

```
[2019-12-02 14:34:33.287]: The resulting CSV file contains 20000 rows
[2019-12-02 14:34:33.287]: Closing the stream due to inactivity
[2019-12-02 14:34:33.290]: Emitting message {"id":"f705ff7c-b18a-4e91-83ac-5a879745d92b","attachments":{"f705ff7c-b18a-4e91-83ac-5a879745d92b.csv":{"content-type":"text/csv","url":"http://steward-service.platform.svc.cluster.local:8200/files/0375788e-5fcd-4931-8208-811c28d1ac3d"}},"body":{"rowCount":20000},"headers":{},"metadata":{}}
```

unfortunately resulting file was only 1 MB large and had 1795 rows in it, not 20000

Attaching result and log of the execution as ZIP file.

[Archive.zip](https://github.com/elasticio/csv-component/files/3911753/Archive.zip)

**Comment by khanzadyan** [comment]
Adding one more note here. A customer tried to do similar experiment and failed. The CSV component reports an error:

```
TypeError: timeout is not a function
    at /home/apprunner/lib/actions/write.js:55:34
    at new Promise (<anonymous>)
    at TaskExec.ProcessAction (/home/apprunner/lib/actions/write.js:55:11)
    at /home/apprunner/node_modules/elasticio-sailor-nodejs/lib/executor.js:29:58
    at new Promise (<anonymous>)
    at TaskExec.process (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/executor.js:28:5)
    at processMessageWithModule (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/sailor.js:350:22)
    at Sailor.doProcess (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/sailor.js:309:20)
    at doProcess.next (<anonymous>)
    at onFulfilled (/home/apprunner/node_modules/co/index.js:65:19)
    at _fulfilled (/home/apprunner/node_modules/q/q.js:834:54)
    at /home/apprunner/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/home/apprunner/node_modules/q/q.js:796:13)
    at /home/apprunner/node_modules/q/q.js:857:14
    at runSingle (/home/apprunner/node_modules/q/q.js:137:13)
    at flush (/home/apprunner/node_modules/q/q.js:125:13)
```

It is unclear how the CSV file writing is working under large numbers of incoming messages. Could it be that the flow control (to be release with with #70 ) would help?

**Comment by zubairov** [comment]
Still an issue - duplicate of #54

**Comment by HannaTrotsenko** [comment]
not relevant as component is deprecated
