### ISSUE TITLE
Error happened: Cannot read property 'separator' of undefined

### ISSUE THREAD

**Issue by vdidushko** [elasticio/csv-component#50]
The flow:

![Screenshot from 2019-12-16 18-07-24](https://user-images.githubusercontent.com/48764578/70922936-a3b01880-202f-11ea-8880-9dd6fa462858.png)

![Screenshot from 2019-12-16 18-09-04](https://user-images.githubusercontent.com/48764578/70922963-b0cd0780-202f-11ea-94a8-29461222b88f.png)

With the latest version of the component ( v19 ), when you retrieve a sample, you get 

```TypeError: Cannot read property 'separator' of undefined

at onFulfilled (/home/apprunner/node_modules/co/index.js:65:19)

at runSingle (/home/apprunner/node_modules/elasticio-sailor-nodejs/node_modules/q/q.js:137:13)

[INFO  tini (1)] Main child exited normally (with status '1')

Error happened: Cannot read property 'separator' of undefined

at Sailor.gen (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/sailor.js:147:20)

at gen.next (<anonymous>)

at _fulfilled (/home/apprunner/node_modules/elasticio-sailor-nodejs/node_modules/q/q.js:834:54)

at flush (/home/apprunner/node_modules/elasticio-sailor-nodejs/node_modules/q/q.js:125:13)

at _combinedTickCallback (internal/process/next_tick.js:95:7)

at Promise (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/sailor.js:149:51)

at self.promiseDispatch.done (/home/apprunner/node_modules/elasticio-sailor-nodejs/node_modules/q/q.js:863:30)

at /home/apprunner/node_modules/elasticio-sailor-nodejs/node_modules/q/q.js:857:14

at process._tickCallback (internal/process/next_tick.js:161:9)

at Object.init (/home/apprunner/lib/actions/write.js:25:31)

at Promise (<anonymous>)

at Promise.promise.promiseDispatch (/home/apprunner/node_modules/elasticio-sailor-nodejs/node_modules/q/q.js:796:13)

TypeError: Cannot read property 'separator' of undefined

at onFulfilled (/home/apprunner/node_modules/co/index.js:65:19)

at runSingle (/home/apprunner/node_modules/elasticio-sailor-nodejs/node_modules/q/q.js:137:13)

[INFO  tini (1)] Main child exited normally (with status '1')```


By the way, you can retrieve a sample with v16 version of the component.

**Comment by vdidushko** [comment]
You can retrieve a sample with v16 version of the component.
![Screenshot from 2019-12-16 18-19-02](https://user-images.githubusercontent.com/48764578/70923804-2b4a5700-2031-11ea-872c-1c2065050192.png)

**Comment by jhorbulyk** [comment]
Hopefully will be solved by #96 & #97
